# Generated by Django 5.2.7 on 2025-10-15 13:37

import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_images"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="get_full_name",
                        unique=True,
                    ),
                ),
                ("birthday", models.DateField(null=True)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("position", models.CharField(null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select Gender"),
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select Blood Group"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("prescriptions", models.TextField(blank=True)),
                ("treatment_details", models.TextField(blank=True)),
                ("diagnoses", models.TextField(blank=True, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateField(auto_now=True)),
                ("calories", models.CharField(blank=True, null=True)),
                ("protein", models.CharField(blank=True, null=True)),
                ("carbs", models.CharField(blank=True, null=True)),
                ("fat", models.CharField(blank=True, null=True)),
                ("dietary_restrictions", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        default="default.jpg", upload_to="profile_images"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, choices=[("Dr.", "Dr."), ("PhD", "PhD")]
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                ("birthday", models.DateField(null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="get_full_name",
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Manager", "Manager"),
                            ("Trainer", "Trainer"),
                            ("Physical Therapist", "Physical Therapist"),
                            ("Dietician", "Dietician"),
                            ("Doctor", "Doctor"),
                            ("Chef", "Chef"),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
