# Generated by Django 5.2.7 on 2025-10-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('athleteprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.athleteprofile')),
            ],
            bases=('profiles.athleteprofile',),
        ),
        migrations.RenameField(
            model_name='athleteprofile',
            old_name='medical_records',
            new_name='dietary_restrictions',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('', 'Select Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')]),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='diagnoses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select Gender'), ('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')]),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='prescriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='treatment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
