# Generated by Django 5.2.7 on 2025-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_athleteprofile_user_staffprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleteprofile",
            name="icon",
            field=models.ImageField(default="default.png", upload_to="profile_images"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="icon",
            field=models.ImageField(default="default.png", upload_to="profile_images"),
        ),
    ]
