# Generated by Django 5.2.7 on 2025-10-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_staffprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
