# Generated by Django 5.2.4 on 2025-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_athleteprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
