# Generated by Django 5.2.7 on 2025-10-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('profiles', '0003_staffprofile_birthday'),
    ]

    operations = [
    ]
