# Generated by Django 5.2.7 on 2025-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_0002_initial_0003_staffprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='position',
            field=models.CharField(blank=True, null=True),
        ),
    ]
