# Generated by Django 5.2.7 on 2025-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_athleteprofile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='icon',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
