# Generated by Django 5.2.7 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_athleteprofile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='icon',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/'),
        ),
    ]
