# Generated by Django 5.2.7 on 2025-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_athleteprofile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
