# Generated by Django 5.2.7 on 2025-10-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_athleteprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='age',
        ),
    ]
