# Generated by Django 5.2.7 on 2025-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_athleteprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='icon',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/'),
        ),
    ]
