# Generated by Django 5.2.7 on 2025-10-21 11:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_athleteprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='calories',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='carbs',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='diagnoses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='fat',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='position',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='protein',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='birthday',
            field=models.DateField(),
        ),
    ]
