# Generated by Django 5.2.7 on 2025-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_athleteprofile_additional_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
