# Generated by Django 5.2.6 on 2025-09-30 09:53

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
