# Generated by Django 5.2.4 on 2025-09-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="name",
            new_name="team_name",
        ),
        migrations.AddField(
            model_name="team",
            name="manager",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
