# Generated by Django 5.2.4 on 2025-09-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="team",
            new_name="team_id",
        ),
    ]
