# Generated by Django 5.2.6 on 2025-09-26 11:18

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_team_customuser_team_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
