# Generated by Django 5.2.7 on 2025-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysessions',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
