# Generated by Django 5.2.7 on 2025-10-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('totalfat', models.PositiveIntegerField(default=0)),
                ('totalcarb', models.PositiveIntegerField(default=0)),
                ('totalprotein', models.PositiveIntegerField(default=0)),
                ('calories', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TDEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(max_length=10)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.meals')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(max_length=10)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.trainingsessions')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalPlan',
        ),
        migrations.DeleteModel(
            name='NutritionPlan',
        ),
        migrations.DeleteModel(
            name='TrainingPlan',
        ),
        migrations.DeleteModel(
            name='UniversalPlan',
        ),
    ]
