# Generated by Django 5.2.7 on 2025-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysessions',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
