# Generated by Django 5.2.6 on 2025-10-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_meals_tdee_trainingsessions_weeklymealplan_and_more 2"),
        ("plans", "0002_meals_tdee_trainingsessions_weeklymealplan_and_more"),
    ]

    operations = []
