# Generated by Django 5.2.4 on 2025-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_medicalplan_nutritionplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coach", "Coach"),
                            ("dietitian", "Dietitian"),
                            ("physiotherapist", "Physiotherapist"),
                            ("manager", "Manager"),
                        ],
                        max_length=50,
                    ),
                ),
                ("instructions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
