# Generated by Django 5.2.7 on 2025-10-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_weeklysessions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysessions',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
