<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-14 14:25
=======
# Generated by Django 5.2.7 on 2025-10-16 11:09
>>>>>>> origin

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participating_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
