# Generated by Django 5.2.7 on 2025-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Once"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                help_text="Select daily, weekly or monthly for repeating events.",
                max_length=20,
            ),
        ),
    ]
