# Generated by Django 5.2.7 on 2025-10-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurrence_date", models.DateField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_modified", models.BooleanField(default=False)),
                ("override_title", models.CharField(blank=True, null=True)),
                ("override_start", models.DateTimeField(blank=True, null=True)),
                ("override_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_booking_instances",
                        to="appointments.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
                "unique_together": {("booking", "occurrence_date")},
            },
        ),
    ]
