# Generated by Django 5.2.4 on 2025-10-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0003_alter_booking_booked_by_alter_booking_participants_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "Once"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="recurrence_end",
            field=models.DateField(
                blank=True, help_text="Repetition until when?", null=True
            ),
        ),
    ]
